CREATE DATABASE CHAPA_TU_PROFE
GO

USE CHAPA_TU_PROFE
GO

CREATE TABLE ROL (
ID_ROL INT IDENTITY NOT NULL,
DESCRIPCION VARCHAR(40),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_ROL)
)
GO

CREATE TABLE USUARIO (
ID_USUARIO INT IDENTITY NOT NULL,
ID_ROL INT,
USUARIO VARCHAR(10) UNIQUE,
CONTRASENA VARBINARY(MAX),
NOMBRE VARCHAR(40),
APELLIDO VARCHAR(40),
CORREO VARCHAR(40),
FOTO VARCHAR(50),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_USUARIO),
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
)
GO

CREATE TABLE SEDE (
ID_SEDE INT IDENTITY NOT NULL,
DESCRIPCION VARCHAR(25),
ESTADO CHAR(1),
PRIMARY KEY (ID_SEDE)
)
GO

CREATE TABLE FACULTAD (
ID_FACULTAD INT IDENTITY NOT NULL,
DESCRIPCION VARCHAR(50),
ESTADO CHAR(1),
PRIMARY KEY (ID_FACULTAD)
)
GO

CREATE TABLE CARRERA (
ID_CARRERA INT IDENTITY NOT NULL,
DESCRIPCION VARCHAR(50),
ID_FACULTAD INT,
ID_SEDE INT,
ESTADO CHAR(1),
PRIMARY KEY (ID_CARRERA),
FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD(ID_FACULTAD),
FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
)
GO

CREATE TABLE CURSO (
ID_CURSO INT IDENTITY NOT NULL,
CODIGO_CURSO VARCHAR(10) UNIQUE,
DESCRIPCION VARCHAR(50),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_CURSO)
)
GO

CREATE TABLE CURSO_CARRERA (
ID_CURSO_CARRERA INT IDENTITY NOT NULL,
ID_CURSO INT,
ID_CARRERA INT,
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_CURSO_CARRERA),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
)
GO

CREATE TABLE DOCENTE (
ID_DOCENTE INT IDENTITY NOT NULL,
CODIGO_DOCENTE VARCHAR(10) UNIQUE,
DNI CHAR(8) UNIQUE,
NOMBRE VARCHAR(40),
APELLIDO VARCHAR(40),
CORREO VARCHAR(40),
FOTO VARCHAR(50),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_DOCENTE)
)
GO

CREATE TABLE DOCENTE_CURSO (
ID_DOCENTE_CURSO INT IDENTITY NOT NULL,
ID_DOCENTE INT,
ID_CURSO INT,
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_DOCENTE_CURSO),
FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
)
GO

CREATE TABLE ALUMNO (
ID_ALUMNO INT IDENTITY NOT NULL,
CODIGO_ALUMNO VARCHAR(10) UNIQUE,
DNI CHAR(8) UNIQUE,
NOMBRE VARCHAR(40),
APELLIDO VARCHAR(40),
CORREO VARCHAR(40),
FOTO VARCHAR(50),
TELEFONO VARCHAR(15),
NRO_CICLO INT,
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_ALUMNO)
)
GO

CREATE TABLE AVANCE_ESTUDIO (
ID_PLAN_ESTUDIO INT IDENTITY NOT NULL,
ID_ALUMNO INT,
ID_CARRERA INT,
ESTADO CHAR(1),
PRIMARY KEY (ID_PLAN_ESTUDIO),
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
)
GO

CREATE TABLE AVANCE_ESTUDIO_DET (
ID_PLAN_ESTUDIO_DET INT IDENTITY NOT NULL,
ID_PLAN_ESTUDIO INT,
ID_DOCENTE INT,
ID_CURSO INT,
TIPO CHAR(1), --O: Obligatorio E: Electivo
MODALIDAD CHAR(1), --P: Presencial V:Virtual
NRO_CICLO INT,
ESTADO CHAR(1), --A:Aprobado C:Convalidado E:En curso P:Pendiente 
PRIMARY KEY (ID_PLAN_ESTUDIO_DET),
FOREIGN KEY (ID_PLAN_ESTUDIO) REFERENCES AVANCE_ESTUDIO(ID_PLAN_ESTUDIO),
FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
)
GO

CREATE TABLE CUESTIONARIO (
ID_CUESTIONARIO INT IDENTITY NOT NULL,
NRO_CUESTIONARIO INT,
SECUENCIA INT,
DESCRIPCION VARCHAR(500),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (NRO_CUESTIONARIO,SECUENCIA)
)
GO

CREATE TABLE CALIFICACION (
ID_CALIFICACION INT IDENTITY NOT NULL,
ID_ALUMNO INT,
ID_DOCENTE INT,
ID_CURSO INT,
ID_CARRERA INT,
NRO_CICLO INT,
PUNTAJE_TOTAL INT,
PUNTAJE_PROMEDIO DECIMAL(8,1),
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_CALIFICACION),
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
)
GO

CREATE TABLE CALIFICACION_DET (
ID_CALIFICACION_DETALLE INT IDENTITY NOT NULL,
ID_CALIFICACION INT,
NRO_CUESTIONARIO INT,
SECUENCIA_CUESTIONARIO INT,
PUNTAJE INT,
ESTADO CHAR(1),
USUARIO_REG VARCHAR(10),
FECHA_REG DATETIME,
USUARIO_MOD VARCHAR(10),
FECHA_MOD DATETIME,
PRIMARY KEY (ID_CALIFICACION_DETALLE),
FOREIGN KEY (ID_CALIFICACION) REFERENCES CALIFICACION(ID_CALIFICACION),
FOREIGN KEY (NRO_CUESTIONARIO,SECUENCIA_CUESTIONARIO) REFERENCES CUESTIONARIO(NRO_CUESTIONARIO,SECUENCIA)
)
GO


SELECT * FROM [dbo].[USUARIO];
SELECT * FROM [dbo].[ROL];
select * from [dbo].[FACULTAD];
select * from [dbo].[SEDE];
select * from [dbo].[CARRERA];
select * from [dbo].[CURSO];
select * from [dbo].[CURSO_CARRERA];
select * from [dbo].[DOCENTE];
select * from [dbo].[DOCENTE_CURSO];
select * from [dbo].[ALUMNO];
select * from [dbo].[AVANCE_ESTUDIO];
select * from [dbo].[AVANCE_ESTUDIO_DET];
select * from [dbo].[CUESTIONARIO];
select * from [dbo].[CALIFICACION];
select * from [dbo].[CALIFICACION_DET];


ALTER AUTHORIZATION ON DATABASE::CHAPA_TU_PROFE TO sa;
GO