USE CHAPA_TU_PROFE
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetUser]
@Code VARCHAR(10),
@Password VARCHAR(MAX)
AS
BEGIN
   SET NOCOUNT ON;
   SELECT 
   CASE U.ID_ROL WHEN 1 THEN U.ID_USUARIO ELSE A.ID_ALUMNO END AS UserId
  ,ISNULL(AE.ID_CARRERA,0) AS CareerId
  ,U.ID_ROL AS RolId
  ,U.USUARIO AS Code
  ,U.NOMBRE AS Name
  ,U.APELLIDO AS LastName
  ,U.CORREO AS Email
  ,U.FOTO AS Photo
  ,U.ESTADO AS Status
   FROM dbo.USUARIO AS U
   LEFT JOIN dbo.ALUMNO A ON A.CODIGO_ALUMNO = U.USUARIO AND A.ESTADO = 'A'
   LEFT JOIN dbo.AVANCE_ESTUDIO AE ON AE.ID_ALUMNO = A.ID_ALUMNO
   WHERE U.USUARIO = @Code AND CONVERT(VARCHAR(MAX), DECRYPTBYPASSPHRASE('password', U.CONTRASENA)) = @Password AND U.ESTADO = 'A'
END
GO

EXEC [dbo].[uspGetUser] 'admin','123456'
GO
