USE CHAPA_TU_PROFE
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetUser]
@Code VARCHAR(10),
@Password VARCHAR(MAX)
AS
BEGIN
   SET NOCOUNT ON;
   SELECT 
   CASE U.ID_ROL WHEN 1 THEN U.ID_USUARIO ELSE A.ID_ALUMNO END AS UserId
  ,ISNULL(AE.ID_CARRERA,0) AS CareerId
  ,ISNULL(A.NRO_CICLO,0) AS CycleNumber
  ,U.ID_ROL AS RolId
  ,U.USUARIO AS Code
  ,U.NOMBRE AS Name
  ,U.APELLIDO AS LastName
  ,U.CORREO AS Email
  ,U.FOTO AS Photo
  ,U.ESTADO AS Status
   FROM dbo.USUARIO AS U
   LEFT JOIN dbo.ALUMNO A ON A.CODIGO_ALUMNO = U.USUARIO AND A.ESTADO = 'A'
   LEFT JOIN dbo.AVANCE_ESTUDIO AE ON AE.ID_ALUMNO = A.ID_ALUMNO
   WHERE U.USUARIO = @Code AND CONVERT(VARCHAR(MAX), DECRYPTBYPASSPHRASE('password', U.CONTRASENA)) = @Password AND U.ESTADO = 'A'
END
GO

EXEC [dbo].[uspGetUser] 'U20150713','12345'
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetCourses]
@StudentId INT,
@CareerId INT
AS
BEGIN
   SET NOCOUNT ON;
   SELECT 
   C.ID_CURSO AS CourseId
  ,C.CODIGO_CURSO AS Code
  ,C.DESCRIPCION AS Description
  ,AED.ESTADO AS Status
   FROM dbo.AVANCE_ESTUDIO AE
   INNER JOIN dbo.AVANCE_ESTUDIO_DET AED ON AED.ID_PLAN_ESTUDIO = AE.ID_PLAN_ESTUDIO
   INNER JOIN dbo.CURSO C ON C.ID_CURSO = AED.ID_CURSO
   WHERE AE.ID_ALUMNO = @StudentId AND AE.ID_CARRERA = @CareerId
END
GO

EXEC [dbo].[uspGetCourses] 2,2
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetTeachers]
@CourseId INT
AS
BEGIN
   SET NOCOUNT ON;
   SELECT 
   D.ID_DOCENTE AS TeacherId,
   D.CODIGO_DOCENTE AS Code,
   D.NOMBRE + ' ' + D.APELLIDO AS Name,
   CAST(AVG(C.PUNTAJE_PROMEDIO) AS DECIMAL(8,1)) AS QualificationTotal
   FROM dbo.DOCENTE D
   INNER JOIN dbo.DOCENTE_CURSO DC ON DC.ID_DOCENTE = D.ID_DOCENTE
   INNER JOIN dbo.CALIFICACION C ON C.ID_DOCENTE = D.ID_DOCENTE
   WHERE DC.ID_CURSO = @CourseId
   GROUP BY  D.ID_DOCENTE, D.CODIGO_DOCENTE, D.NOMBRE + ' ' + D.APELLIDO
END
GO

EXEC [dbo].[uspGetTeachers] 2
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetTeachersDetail]
@TeacherId INT
AS
BEGIN
   SET NOCOUNT ON;
   SELECT 
   CD.SECUENCIA_CUESTIONARIO AS SequenceQuestion,
   CU.DESCRIPCION AS Description,
   CAST(CAST(SUM(CD.PUNTAJE) AS DECIMAL(8,1))/CAST(COUNT(CD.PUNTAJE) AS DECIMAL(8,1)) AS DECIMAL(8,1)) AS QuestionScoreTotal
   FROM dbo.CALIFICACION_DET CD 
   INNER JOIN dbo.CALIFICACION C ON C.ID_CALIFICACION = CD.ID_CALIFICACION
   INNER JOIN dbo.CUESTIONARIO CU ON CU.NRO_CUESTIONARIO = CD.NRO_CUESTIONARIO AND CU.SECUENCIA = CD.SECUENCIA_CUESTIONARIO
   WHERE C.ID_DOCENTE = @TeacherId
   GROUP BY CD.SECUENCIA_CUESTIONARIO, CU.DESCRIPCION
   ORDER BY CD.SECUENCIA_CUESTIONARIO
END
GO

EXEC [dbo].[uspGetTeachersDetail] 1
GO

CREATE OR ALTER PROCEDURE [dbo].[uspGetQuestionnaire]
@StudentId INT,
@TeacherId INT,
@CourseId INT,
@CycleNumber INT
AS
BEGIN
    SET NOCOUNT ON;
	DECLARE @count INT;
    SET @count = (SELECT COUNT(1) FROM dbo.CALIFICACION WHERE ID_ALUMNO = @StudentId AND ID_DOCENTE = @TeacherId AND ID_CURSO = @CourseId AND NRO_CICLO = @CycleNumber)

	IF @count > 0 
		SELECT
		0 AS QuestionNumber,
		0 AS SequenceQuestion,
		'-' AS Description
		FROM dbo.CUESTIONARIO C
	ELSE
		SELECT
		C.NRO_CUESTIONARIO AS QuestionNumber,
		C.SECUENCIA AS SequenceQuestion,
		C.DESCRIPCION AS Description
		FROM dbo.CUESTIONARIO C
		WHERE C.ESTADO = 'A'
END
GO

EXEC [dbo].[uspGetQuestionnaire] 1,1,1,7
GO

CREATE OR ALTER PROCEDURE [dbo].[uspAddQualify]
@StudentId INT,
@TeacherId INT,
@CourseId INT,
@CareerId INT,
@CycleNumber INT,
@QualificationTotal INT,
@QuestionScoreAverage DECIMAL(8,1),
@User VARCHAR(10),
@Code INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [dbo].[CALIFICACION] ([ID_ALUMNO],[ID_DOCENTE],[ID_CURSO],[ID_CARRERA],[NRO_CICLO],[PUNTAJE_TOTAL],[PUNTAJE_PROMEDIO],[ESTADO],[USUARIO_REG],[FECHA_REG])
	VALUES (@StudentId, @TeacherId, @CourseId, @CareerId, @CycleNumber, @QualificationTotal, @QuestionScoreAverage, 'A', @User, GETDATE())

	SELECT @code = C.ID_CALIFICACION FROM [dbo].[CALIFICACION] C WHERE C.ID_CALIFICACION = SCOPE_IDENTITY()
END
GO

DECLARE @MyCode int;  
EXEC [dbo].[uspAddQualify]  1,1,1,1,2,10,5.0,'user', @code = @MyCode OUTPUT;
GO


CREATE OR ALTER PROCEDURE [dbo].[uspAddQualifyDetail]
@QualifyId INT,
@QuestionNumber INT,
@QuestionSequence INT,
@Score INT,
@User VARCHAR(10),
@Code INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [dbo].[CALIFICACION_DET] ([ID_CALIFICACION],[NRO_CUESTIONARIO],[SECUENCIA_CUESTIONARIO],[PUNTAJE],[ESTADO],[USUARIO_REG],[FECHA_REG])
    VALUES(@QualifyId, @QuestionNumber, @QuestionSequence, @Score, 'A', @User, GETDATE())

	SELECT @code = CD.ID_CALIFICACION_DETALLE  FROM [dbo].[CALIFICACION_DET] CD WHERE CD.ID_CALIFICACION_DETALLE = SCOPE_IDENTITY()
END
GO

DECLARE @MyCode int;  
EXEC [dbo].[uspAddQualifyDetail] 8,1,2,5,'user',@code = @MyCode OUTPUT;
GO

